language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - hhvm-nightly

matrix:
  fast_finish: true

  allow_failures:
      - php: hhvm
      - php: hhvm-nightly

  include:
    - php: 5.6
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 5.6
      env: COMPOSER_FLAG=--prefer-stable
    - php: 7.0
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 7.0
      env: COMPOSER_FLAG=--prefer-stable
    - php: 7.1
      env: COMPOSER_FLAG=--prefer-lowest
    - php: 7.1
      env: COMPOSER_FLAG=--prefer-stable

before_script:
  # Composer
  - travis_retry composer install --no-interaction
  # Coverage
  - if [[ "$TRAVIS_PHP_VERSION" == "7.0" && "$COMPOSER_FLAG" == "" ]]; then COVERAGE=1; fi
  # Phpstan
  - if [[ "$TRAVIS_PHP_VERSION" == "7.1" && "$COMPOSER_FLAG" == "" ]]; then PHPSTAN=1; fi

script:
  # Quality Assurance
  - composer run-script qa-linter
  - composer run-script qa-codesniffer

  # Nette\Tester
  - composer run-script ci

  # Nette\Tester + CodeCoverage
  - if [ "$COVERAGE" != "" ]; then composer run-script ci-coverage; fi

  # PHPSTAN
  - if [ "$PHPSTAN" != "" ]; then composer require phpstan/phpstan:^0.6.4; fi
  - if [ "$PHPSTAN" != "" ]; then composer run-script qa-phpstan; fi

after_script:
  # Coverage (Coveralls)
  - if [ "$COVERAGE" != "" ]; then wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar; fi
  - if [ "$COVERAGE" != "" ]; then php coveralls.phar --verbose --config tests/.coveralls.yml; fi

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
